/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LetterContent {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'owner' : Principal,
  'createdAt' : bigint,
  'tone' : string,
  'letterType' : LetterType,
  'updatedAt' : bigint,
  'fontFamily' : string,
}
export type LetterType = { 'informationRequestLetter' : null } |
  { 'application' : null } |
  { 'certificateOfAppreciation' : null } |
  { 'governmentPressNote' : null } |
  { 'officeLetter' : null } |
  { 'complaintLetter' : null } |
  { 'petition' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createLetter' : ActorMethod<
    [
      {
        'title' : string,
        'content' : string,
        'tone' : string,
        'letterType' : LetterType,
        'fontFamily' : string,
      },
    ],
    bigint
  >,
  'deleteLetter' : ActorMethod<[bigint], undefined>,
  'getAccessibleLettersSortedByType' : ActorMethod<[], Array<LetterContent>>,
  'getAllLetters' : ActorMethod<[], Array<LetterContent>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLetterById' : ActorMethod<[bigint], LetterContent>,
  'getLettersByType' : ActorMethod<[LetterType], Array<LetterContent>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'searchLettersByTitle' : ActorMethod<[string], Array<LetterContent>>,
  'updateLetter' : ActorMethod<
    [
      {
        'id' : bigint,
        'title' : string,
        'content' : string,
        'tone' : string,
        'letterType' : LetterType,
        'fontFamily' : string,
      },
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];