/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LetterType = IDL.Variant({
  'informationRequestLetter' : IDL.Null,
  'application' : IDL.Null,
  'certificateOfAppreciation' : IDL.Null,
  'governmentPressNote' : IDL.Null,
  'officeLetter' : IDL.Null,
  'complaintLetter' : IDL.Null,
  'petition' : IDL.Null,
});
export const LetterContent = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : IDL.Int,
  'tone' : IDL.Text,
  'letterType' : LetterType,
  'updatedAt' : IDL.Int,
  'fontFamily' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createLetter' : IDL.Func(
      [
        IDL.Record({
          'title' : IDL.Text,
          'content' : IDL.Text,
          'tone' : IDL.Text,
          'letterType' : LetterType,
          'fontFamily' : IDL.Text,
        }),
      ],
      [IDL.Nat],
      [],
    ),
  'deleteLetter' : IDL.Func([IDL.Nat], [], []),
  'getAccessibleLettersSortedByType' : IDL.Func(
      [],
      [IDL.Vec(LetterContent)],
      ['query'],
    ),
  'getAllLetters' : IDL.Func([], [IDL.Vec(LetterContent)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLetterById' : IDL.Func([IDL.Nat], [LetterContent], ['query']),
  'getLettersByType' : IDL.Func(
      [LetterType],
      [IDL.Vec(LetterContent)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'searchLettersByTitle' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LetterContent)],
      ['query'],
    ),
  'updateLetter' : IDL.Func(
      [
        IDL.Record({
          'id' : IDL.Nat,
          'title' : IDL.Text,
          'content' : IDL.Text,
          'tone' : IDL.Text,
          'letterType' : LetterType,
          'fontFamily' : IDL.Text,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LetterType = IDL.Variant({
    'informationRequestLetter' : IDL.Null,
    'application' : IDL.Null,
    'certificateOfAppreciation' : IDL.Null,
    'governmentPressNote' : IDL.Null,
    'officeLetter' : IDL.Null,
    'complaintLetter' : IDL.Null,
    'petition' : IDL.Null,
  });
  const LetterContent = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : IDL.Int,
    'tone' : IDL.Text,
    'letterType' : LetterType,
    'updatedAt' : IDL.Int,
    'fontFamily' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createLetter' : IDL.Func(
        [
          IDL.Record({
            'title' : IDL.Text,
            'content' : IDL.Text,
            'tone' : IDL.Text,
            'letterType' : LetterType,
            'fontFamily' : IDL.Text,
          }),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteLetter' : IDL.Func([IDL.Nat], [], []),
    'getAccessibleLettersSortedByType' : IDL.Func(
        [],
        [IDL.Vec(LetterContent)],
        ['query'],
      ),
    'getAllLetters' : IDL.Func([], [IDL.Vec(LetterContent)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLetterById' : IDL.Func([IDL.Nat], [LetterContent], ['query']),
    'getLettersByType' : IDL.Func(
        [LetterType],
        [IDL.Vec(LetterContent)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'searchLettersByTitle' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LetterContent)],
        ['query'],
      ),
    'updateLetter' : IDL.Func(
        [
          IDL.Record({
            'id' : IDL.Nat,
            'title' : IDL.Text,
            'content' : IDL.Text,
            'tone' : IDL.Text,
            'letterType' : LetterType,
            'fontFamily' : IDL.Text,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };