/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LetterContent {
    id: bigint;
    title: string;
    content: string;
    owner: Principal;
    createdAt: bigint;
    tone: string;
    letterType: LetterType;
    updatedAt: bigint;
    fontFamily: string;
}
export enum LetterType {
    informationRequestLetter = "informationRequestLetter",
    application = "application",
    certificateOfAppreciation = "certificateOfAppreciation",
    governmentPressNote = "governmentPressNote",
    officeLetter = "officeLetter",
    complaintLetter = "complaintLetter",
    petition = "petition"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createLetter(creationRequest: {
        title: string;
        content: string;
        tone: string;
        letterType: LetterType;
        fontFamily: string;
    }): Promise<bigint>;
    deleteLetter(letterId: bigint): Promise<void>;
    getAccessibleLettersSortedByType(): Promise<Array<LetterContent>>;
    getAllLetters(): Promise<Array<LetterContent>>;
    getCallerUserRole(): Promise<UserRole>;
    getLetterById(letterId: bigint): Promise<LetterContent>;
    getLettersByType(letterType: LetterType): Promise<Array<LetterContent>>;
    isCallerAdmin(): Promise<boolean>;
    searchLettersByTitle(searchTerm: string): Promise<Array<LetterContent>>;
    updateLetter(updateRequest: {
        id: bigint;
        title: string;
        content: string;
        tone: string;
        letterType: LetterType;
        fontFamily: string;
    }): Promise<void>;
}
import type { LetterContent as _LetterContent, LetterType as _LetterType, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createLetter(arg0: {
        title: string;
        content: string;
        tone: string;
        letterType: LetterType;
        fontFamily: string;
    }): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createLetter(to_candid_record_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLetter(to_candid_record_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteLetter(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLetter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLetter(arg0);
            return result;
        }
    }
    async getAccessibleLettersSortedByType(): Promise<Array<LetterContent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccessibleLettersSortedByType();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccessibleLettersSortedByType();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLetters(): Promise<Array<LetterContent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLetters();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLetters();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLetterById(arg0: bigint): Promise<LetterContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getLetterById(arg0);
                return from_candid_LetterContent_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLetterById(arg0);
            return from_candid_LetterContent_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLettersByType(arg0: LetterType): Promise<Array<LetterContent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLettersByType(to_candid_LetterType_n4(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLettersByType(to_candid_LetterType_n4(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async searchLettersByTitle(arg0: string): Promise<Array<LetterContent>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchLettersByTitle(arg0);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchLettersByTitle(arg0);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLetter(arg0: {
        id: bigint;
        title: string;
        content: string;
        tone: string;
        letterType: LetterType;
        fontFamily: string;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLetter(to_candid_record_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLetter(to_candid_record_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_LetterContent_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LetterContent): LetterContent {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_LetterType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LetterType): LetterType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: string;
    owner: Principal;
    createdAt: bigint;
    tone: string;
    letterType: _LetterType;
    updatedAt: bigint;
    fontFamily: string;
}): {
    id: bigint;
    title: string;
    content: string;
    owner: Principal;
    createdAt: bigint;
    tone: string;
    letterType: LetterType;
    updatedAt: bigint;
    fontFamily: string;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        owner: value.owner,
        createdAt: value.createdAt,
        tone: value.tone,
        letterType: from_candid_LetterType_n9(_uploadFile, _downloadFile, value.letterType),
        updatedAt: value.updatedAt,
        fontFamily: value.fontFamily
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    informationRequestLetter: null;
} | {
    application: null;
} | {
    certificateOfAppreciation: null;
} | {
    governmentPressNote: null;
} | {
    officeLetter: null;
} | {
    complaintLetter: null;
} | {
    petition: null;
}): LetterType {
    return "informationRequestLetter" in value ? LetterType.informationRequestLetter : "application" in value ? LetterType.application : "certificateOfAppreciation" in value ? LetterType.certificateOfAppreciation : "governmentPressNote" in value ? LetterType.governmentPressNote : "officeLetter" in value ? LetterType.officeLetter : "complaintLetter" in value ? LetterType.complaintLetter : "petition" in value ? LetterType.petition : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LetterContent>): Array<LetterContent> {
    return value.map((x)=>from_candid_LetterContent_n7(_uploadFile, _downloadFile, x));
}
function to_candid_LetterType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LetterType): _LetterType {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: string;
    tone: string;
    letterType: LetterType;
    fontFamily: string;
}): {
    id: bigint;
    title: string;
    content: string;
    tone: string;
    letterType: _LetterType;
    fontFamily: string;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        tone: value.tone,
        letterType: to_candid_LetterType_n4(_uploadFile, _downloadFile, value.letterType),
        fontFamily: value.fontFamily
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    tone: string;
    letterType: LetterType;
    fontFamily: string;
}): {
    title: string;
    content: string;
    tone: string;
    letterType: _LetterType;
    fontFamily: string;
} {
    return {
        title: value.title,
        content: value.content,
        tone: value.tone,
        letterType: to_candid_LetterType_n4(_uploadFile, _downloadFile, value.letterType),
        fontFamily: value.fontFamily
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LetterType): {
    informationRequestLetter: null;
} | {
    application: null;
} | {
    certificateOfAppreciation: null;
} | {
    governmentPressNote: null;
} | {
    officeLetter: null;
} | {
    complaintLetter: null;
} | {
    petition: null;
} {
    return value == LetterType.informationRequestLetter ? {
        informationRequestLetter: null
    } : value == LetterType.application ? {
        application: null
    } : value == LetterType.certificateOfAppreciation ? {
        certificateOfAppreciation: null
    } : value == LetterType.governmentPressNote ? {
        governmentPressNote: null
    } : value == LetterType.officeLetter ? {
        officeLetter: null
    } : value == LetterType.complaintLetter ? {
        complaintLetter: null
    } : value == LetterType.petition ? {
        petition: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
